# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12DHfjoTbKnD2A5glzvwrFJv81XdpI4yO
"""

#print
#sep 분리문자
print('010', "1234", "5678", sep="-")

#end 종료문자
print('010', end="")
print('hi')

print('010', "1234", sep="-", end="-")
print('5678')

#나누기
print('실제 값 : ' + str(6/4))
#몫 구하기
print('몫 : ' + str(6//4))

print(True | False)
print(True & False)

sentence = '나는 소년입니다'
print(sentence)
sentence2 = '파이썬은 쉬워요'
print(sentence2)
sentence3 = '''
나는 소년이고,
파이썬은 쉬워요
'''
print(sentence3)

jumin = "990120-1234567"

print("성별 : " + jumin[7])
print("연 : " + jumin[0:2])
print("월 : " + jumin[2:4])
print("일 : " + jumin[4:6])

print("생년월일 : " + jumin[:6])
print("뒤 7자리 : " + jumin[7:])
print("뒤 7자리 (뒤에부터) : " + jumin[-7:])

#방법 1
print("나는 %d살 입니다." % 20)
print("나는 %s살 입니다." % 20)
print("나는 %s색과 %s색을 좋아해요." % ("파란", "빨간"))
'''
  age=21
  color="빨간"
  print("나는 %s살이고, %s색을 좋아해요.1" % (age, color))
'''

#방법 2
print("나는 {}살 입니다.".format(20))
print("나는 {}색과 {}색을 좋아해요.".format("파란", "빨간"))
print("나는 {0}색과 {1}색을 좋아해요.".format("파란", "빨간"))
print("나는 {1}색과 {0}색을 좋아해요.".format("파란", "빨간"))

#방법 3
print("나는 {age}살이고, {color}색을 좋아해요.".format(age = 20, color = "빨간"))
print("나는 {age}살이고, {color}색을 좋아해요.".format(age = 20, color = "빨간"))

#방법4
age = 20
color = "빨간"
print(f"나는 {age}살이며, {color}색을 좋아해요.")

print("저는 \"나도코딩\"입니다.")
print("저는 \'나도코딩\'입니다.")
print("C:\\Users\\Nadocoding\\Desktop")
print("Red Apple\rPine")
print("Redd\bApple")
print("Red\tApple")

#리스트

subway1 = 10
subway2 = 20
subway3 = 30

subway = [10, 20, 30]
print(subway)

subway = ["유재석", "조세호", "박명수"]
print(subway)

#조세호 인덱스 검색
print(subway.index("조세호"))

#하하 뒤에 붙이기
subway.append("하하")
print(subway)

#1번 인덱스에 정형돈 삽입
subway.insert(1, "정형돈")
print(subway)

#뒤에서부터 꺼내기
print(subway.pop())
print(subway)

print(subway.pop())
print(subway)

print(subway.pop())
print(subway)

#값으로 하나 삭제
subway.remove("유재석")
print(subway)

#같은 이름의 사람이 몇 명
subway.append("유재석")
print(subway)
print(subway.count("유재석"))

#정렬
num_list = [5,4,3,2,1]
num_list.sort()
print(num_list)

num_list.reverse()
print(num_list)

#모두 지우기
num_list.clear()
print(num_list)

#리스트 확장
num_list = [5,4,3,2,1]
mix_list = ["조세호", 20 , True]

num_list.extend(mix_list)
print(num_list)

#사전
# (키, 값)
# 키가 중복되면 안됨 나중에 추가한 값으로 덮어쓰기 됨

cabinet = {3:"유재석",100:"김태호"}
print(cabinet[3])
print(cabinet[100])

print(cabinet.get(3))

# 값이 없는 경우 문자 출력
print(cabinet.get(5, "사용 가능"))

print(3 in cabinet)
print(5 in cabinet)

cabinet = {"A-3":"유재석", "B-100":"김태호"}
print(cabinet["A-3"])
print(cabinet["B-100"])

#새 손님
print(cabinet)
cabinet["A-3"] = "김종국"
cabinet["C-20"] = "조세호"
print(cabinet)

#간 손님
del cabinet["A-3"]
print(cabinet)

# key 들만 출력
print(cabinet.keys())

# value 들만 출력
print(cabinet.values())

# key, value 쌍으로 출력
print(cabinet.items())

# 모두 지우기
cabinet.clear()
print(cabinet)

#튜플
# 속도가 리스트보다 빠름
# 추가, 변경 안됨
menu = ("돈까스", "치즈까스")

print(menu[0])
print(menu[1])

name, age, hobby = ("김종국", 20, "코딩")
print(name, age, hobby)

#세트
# 중복 안됨, 순서 없음
my_set = {1,2,3,4,5}
print(my_set)

java = {"유재석", "김태호", "양세형"}
python = set(["유재석", "박명수"])

# 교집합
print(java & python)
print(java.intersection(python))

# 합집합
print(java | python)
print(java.union(python))

# 차집합
print(java - python)
print(java.difference(python))

# python 하는 사람 늘리기
python.add("김태호")
print(python)

# java 없애기
java.remove("김태호")
print(java)

menu = {"집합", "우유", "주스"}
print(menu, type(menu))

menu = list(menu)
print(menu, type(menu))

menu = tuple(menu)
print(menu, type(menu))

menu = set(menu)
print(menu, type(menu))

#if문

weather = input("오늘 날씨는 어때요?")
if weather == "비" or weather == "눈":
  print("우산을 챙기세요")
elif weather == "미세먼지":
  print("마스크를 챙기세요")
else:
  print("준비물 필요 없어요")

temp = int(input("기온은 어때요?"))
if 30 <= temp:
  print("너무 더워요. 나가지 마세요")
elif 10 <= temp and temp < 30:
  print("괜찮은 날씨에요")
elif 0 <= temp < 10:
  print("외투를 챙기세요")
else:
  print("너무 추워요. 나가지 마세요")

# for 문

for waiting_no in [0,1,2,3,4]:
  print("대기번호 : {0}".format(waiting_no))

for waiting_no in range(1, 6):
  print("대기번호 : {0}".format(waiting_no))

#리스트
starbucks = ["아이언맨", "토르", "아이엠 그루트"]
for customer in starbucks:
  print("{0}, 커피가 준비되었습니다.".format(customer))

# while 문

customer = "토르"
index = 5
while index >= 1:
  print("{0}, 커피가 준비되었습니다. {1} 번 남았어요.".format(customer, index))
  index -= 1
  if index == 0 :
    print("커피 폐기")

customer = "토르"
person = "Unknown"

while person != customer :
  print("{0}, 커피가 준비 되었습니다.".format(customer))
  person = input("이름이 어떻게 되세요? ")